[project]
name = "agents-sdk-cli-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.12.1",
    "openai-agents>=0.1.0",
    "prompt-toolkit>=3.0.51",
    "uvicorn>=0.35.0",
]
